version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 8081:8081
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres:postgres@db/db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
