version: '3.1'
include:
  - docker-compose-aux.yml
services:
  server:
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_POSTGRES_URL: postgresql://postgres:postgres@db/db
    build:
      context: .
