[http]
port = 8080

[log]
level = "debug"

[postgres]
# WARNING: this is just to make submitting this task easier.
# Don't actually do this in the real projects.
url = "postgresql://postgres:postgres@localhost:5432/db"
poolmax = 2